#include <EEPROM.h>

void setup()
{
  Serial.begin(9600);
  digitalWrite(A0, HIGH);
  unsigned int a = 46;
  EEPROM.write(2, 43); //length of chars

  digitalWrite(A0, LOW);
  EEPROM.write(3, 'A');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 3); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(4, 'B');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 19); a++;
  EEPROM.write(a, 28); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(5, 'C');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 19); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(6, 'D');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 19); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(7, 'E');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(8, 'F');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(9, 'G');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 29); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(10, 'H');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(11, 'I');
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(12, 'J');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(13, 'K');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 176); a++;
  EEPROM.write(a, 160); a++;
  EEPROM.write(a, 176); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 160); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(14, 'L');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(15, 'M');
  EEPROM.write(a, 94); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(16, 'N');
  EEPROM.write(a, 94); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(17, 'O');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 19); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(18, 'P');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(19, 'Q');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 10); a++;
  EEPROM.write(a, 19); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(20, 'R');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 160); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 160); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(21, 'S');
  EEPROM.write(a, 89); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 3); a++;
  EEPROM.write(a, 21); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(22, 'T');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(23, 'U');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(24, 'V');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 30); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 27); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(25, 'W');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 224); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 241); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 161); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 176); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(26, 'X');
  EEPROM.write(a, 94); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 10); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 10); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(27, 'Y');
  EEPROM.write(a, 94); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 14); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(28, 'Z');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 27); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 27); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(29, '0');
  EEPROM.write(a, 73); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(30, '1');
  EEPROM.write(a, 48); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 177); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(31, '2');
  EEPROM.write(a, 72); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(32, '3');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 193); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(33, '4');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 22); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(34, '5');
  EEPROM.write(a, 65); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(35, '6');
  EEPROM.write(a, 72); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(36, '7');
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(37, '8');
  EEPROM.write(a, 73); a++;
  EEPROM.write(a, 25); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(38, '9');
  EEPROM.write(a, 73); a++;
  EEPROM.write(a, 23); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 49); a++;
  EEPROM.write(a, 17); a++;
  EEPROM.write(a, 64); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(39, '.');
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(40, '*'); //°
  EEPROM.write(a, 56); a++;
  EEPROM.write(a, 22); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 2); a++;
  EEPROM.write(a, 20); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(41, '%');
  EEPROM.write(a, 81); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 15); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 1); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(42, ' ');
  EEPROM.write(a, 80); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(43, ':');
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 16); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(44, '('); //left arrow
  EEPROM.write(a, 32); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 11); a++;
  EEPROM.write(a, 26); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, LOW);
  EEPROM.write(45, ')'); // right arrow
  EEPROM.write(a, 32); a++;
  EEPROM.write(a, 225); a++;
  EEPROM.write(a, 240); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;
  EEPROM.write(a, 0); a++;

  digitalWrite(A0, HIGH);
  EEPROM.write(0, (int)(a >> 8)); //next address 1
  EEPROM.write(1, (int)(a & 0xFF)); //next address 2
}

void loop()
{
  digitalWrite(A0, LOW);
}
